apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2026-07-03T21:27:55Z"
  generation: 1
  labels:
    app: test-repo
  name: test-repo
  namespace: snk
  resourceVersion: "168704"
  uid: c82b3bd0-2ebe-4dbd-b50e-48ad158a6a74
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-repo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-repo
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
